### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by josephgupkim** [aboseman1/capstone#3]
In regards to your media queries, don't forget to add the viewport meta tag to the “head” section of your html file:
meta name="viewport" content="width=device-width, initial-scale=1"

This will ensure that your media queries are applied when a change in screen size occurs.

Also, it's common practice to link in the custom stylesheet AFTER the reset stylesheet so that your custom styles can override the ones that were reset.

The only area I'd have you focus a bit more on is the "Start Learning" section where the text inside the boxes poke out if the screen width is wide.

Other than that, your project looks amazing! Most importantly, the overall structure of the site looks identical to the design spec, so great job!

**Comment by aboseman1** [comment]
Hey, that is an area where I struggled the most on. i also find that the containers of the sections that store the background colors does not always extend the full length of the content so I was struggling to find a way to fix that as well.
