### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [aboseman1/capstone#4]
Awesome job on completing this final project and with it, proving your understanding of the many important concepts that were revealed throughout the course!
Project notes:

- Utilization of indentations and whitespace.
- Addition of comments.
- Accurate to mobile design spec.
- Accurate to desktop design spec.
- Only missing viewport meta tag.

Overall, superb work! Keep it up!
Grade: Meets expectation.

**Comment by aboseman1** [comment]
Thanks a lot for that feedback! It has been a great course and I look forward to further perfecting my craft. Any advice on resources that i can use to learn more about media queries and also bootstrap, JS, and JQuery?
